services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: digital_hunter
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    networks:
    - digital_hunter2




  # queries:
  #   build:
  #     context: .
  #     dockerfile: queries/Dockerfile
  #   restart: unless-stopped
  #   env_file: .env
  #   networks:
  #   - digital_hunter2
  #   depends_on:
  #   - mysql
    
    

volumes:
  mysql_data:

networks:
  digital_hunter2:
    driver: bridge